//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPeliculas
    {
        public byte IdTipoPelicula { get; set; }
        public string DescripcionTipoPelicula { get; set; }
        public bool EstadoTipoPelicula { get; set; }
    }
}
